export const getStation =  [
    /* 운영회사, 역번호, 연계역, 지선/본선여부, 역명, 개통여부 */
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '802', 'stationId': '802', 'transferLine': '4', 'lineType': '', 'stationName': '별내별가람', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '803', 'stationId': '803', 'transferLine': '', 'lineType': '', 'stationName': '별내중앙', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '804', 'stationId': '804', 'transferLine': 'gyeongchun', 'lineType': '', 'stationName': '별내', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '805', 'stationId': '805', 'transferLine': '', 'lineType': '', 'stationName': '다산', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '806', 'stationId': '806', 'transferLine': '', 'lineType': '', 'stationName': '동구릉', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '807', 'stationId': '807', 'transferLine': 'gyeongjung', 'lineType': '', 'stationName': '구리', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '808', 'stationId': '808', 'transferLine': '', 'lineType': '', 'stationName': '장자호수공원', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '809', 'stationId': '809', 'transferLine': '', 'lineType': '', 'stationName': '암사역사공원', 'status': 0},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '810', 'stationId': '810', 'transferLine': '', 'lineType': '', 'stationName': '암사', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '811', 'stationId': '811', 'transferLine': '5', 'lineType': '', 'stationName': '천호', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '812', 'stationId': '812', 'transferLine': '', 'lineType': '', 'stationName': '강동구청', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '813', 'stationId': '813', 'transferLine': '', 'lineType': '', 'stationName': '몽촌토성', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '814', 'stationId': '814', 'transferLine': '2', 'lineType': '', 'stationName': '잠실', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '815', 'stationId': '815', 'transferLine': '9', 'lineType': '', 'stationName': '석촌', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '816', 'stationId': '816', 'transferLine': '', 'lineType': '', 'stationName': '송파', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '817', 'stationId': '817', 'transferLine': '3', 'lineType': '', 'stationName': '가락시장', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '818', 'stationId': '818', 'transferLine': '', 'lineType': '', 'stationName': '문정', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '819', 'stationId': '819', 'transferLine': '', 'lineType': '', 'stationName': '장지', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '820', 'stationId': '820', 'transferLine': 'suinbundang', 'lineType': '', 'stationName': '복정', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '821', 'stationId': '821', 'transferLine': '', 'lineType': '', 'stationName': '남위례', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '822', 'stationId': '822', 'transferLine': '', 'lineType': '', 'stationName': '산성', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '823', 'stationId': '823', 'transferLine': '', 'lineType': '', 'stationName': '남한산성입구', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '824', 'stationId': '824', 'transferLine': '', 'lineType': '', 'stationName': '단대오거리', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '825', 'stationId': '825', 'transferLine': '', 'lineType': '', 'stationName': '신흥', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '826', 'stationId': '826', 'transferLine': '', 'lineType': '', 'stationName': '수진', 'status': 1},
    { 'companyCode': 'S', 'lineId': '8', 'manageCode': '827', 'stationId': '827', 'transferLine': 'suinbundang', 'lineType': '', 'stationName': '모란', 'status': 1}
]