export const getStation =  [
    /* 운영회사, 역번호, 연계역, 지선/본선여부, 역명, 개통여부 */
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D01', 'stationId': 'D01', 'transferLine': '', 'lineType': '', 'stationName': '용산', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D02', 'stationId': 'D02', 'transferLine': '', 'lineType': '', 'stationName': '국립박물관', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D03', 'stationId': 'D03', 'transferLine': '', 'lineType': '', 'stationName': '동빙고', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D04', 'stationId': 'D04', 'transferLine': '', 'lineType': '', 'stationName': '신사', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D05', 'stationId': 'D05', 'transferLine': '', 'lineType': '', 'stationName': '논현', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D06', 'stationId': 'D06', 'transferLine': '', 'lineType': '', 'stationName': '신논현', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D07', 'stationId': 'D07', 'transferLine': '', 'lineType': '', 'stationName': '강남', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D08', 'stationId': 'D08', 'transferLine': '', 'lineType': '', 'stationName': '양재', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D09', 'stationId': 'D09', 'transferLine': '', 'lineType': '', 'stationName': '양재시민의숲', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D10', 'stationId': 'D10', 'transferLine': '', 'lineType': '', 'stationName': '청계산입구', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D11', 'stationId': 'D11', 'transferLine': '', 'lineType': '', 'stationName': '판교', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D12', 'stationId': 'D12', 'transferLine': '', 'lineType': '', 'stationName': '정자', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D13', 'stationId': 'D13', 'transferLine': '', 'lineType': '', 'stationName': '미금', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D14', 'stationId': 'D14', 'transferLine': '', 'lineType': '', 'stationName': '동천', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D15', 'stationId': 'D15', 'transferLine': '', 'lineType': '', 'stationName': '수지구청', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D16', 'stationId': 'D16', 'transferLine': '', 'lineType': '', 'stationName': '성복', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D17', 'stationId': 'D17', 'transferLine': '', 'lineType': '', 'stationName': '상현', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D18', 'stationId': 'D18', 'transferLine': '', 'lineType': '', 'stationName': '광교중앙', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D19', 'stationId': 'D19', 'transferLine': '', 'lineType': '', 'stationName': '광교', 'status': 1},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D19', 'stationId': 'D19', 'transferLine': '', 'lineType': '', 'stationName': '수원월드컵경기장', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D20', 'stationId': 'D20', 'transferLine': '', 'lineType': '', 'stationName': '동수원', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D21', 'stationId': 'D21', 'transferLine': '', 'lineType': '', 'stationName': '화서', 'status': 0},
        { 'companyCode': 'SB', 'lineId': 'shinbundang', 'manageCode': 'D22', 'stationId': 'D22', 'transferLine': '', 'lineType': '', 'stationName': '호매실', 'status': 0}
]